driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY'] %>
  security_group_ids:  <%= ENV['AWS_SECURITY_GROUPS'] %>
  region: <%= ENV['AWS_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  require_chef_omnibus: true
  subnet_id: <%= ENV['AWS_SUBNET'] %>
  instance_type: <%= ENV['INSTANCE_SIZE'] %>
  associate_public_ip: false
  interface: private
  user_data: <%= ENV['USER_DATA_PATH'] %>
  tags:
    OWNER: <%= ENV['AWS_OWNER_TAG'] %>

provisioner:
  name: chef_zero

transport:
  username: <%= ENV['AWS_USERNAME'] %>
  ssh_key: ~/.ssh/<%= ENV['AWS_SSH_KEY'] %>.pem

platforms:
  - name: <%= ENV['AWS_PLATFORM_NAME'] %>
    driver:
      image_id: <%= ENV['AWS_AMI_ID'] %>


suites:
  - name: default
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[nginx::default]
  - name: modules
    run_list:
      - recipe[nginx::source]
    attributes:
      nginx:
        source:
          modules:
            - nginx::headers_more_module
            - nginx::http_auth_request_module
            - nginx::http_echo_module
            - nginx::http_geoip_module
            - nginx::http_gzip_static_module
            - nginx::http_realip_module
            - nginx::http_spdy_module
            - nginx::http_ssl_module
            - nginx::http_stub_status_module
            - nginx::naxsi_module
            - nginx::ngx_devel_module
            - nginx::ngx_lua_module
            - nginx::openssl_source
            - nginx::upload_progress_module
  - name: other-settings
    run_list:
      - recipe[gd-test-helper::default]
      - recipe[nginx::default]
      - recipe[nginx::authorized_ips]
      - recipe[nginx::ipv6]
      - recipe[nginx::lua]
      - recipe[nginx::ohai_plugin]
      - recipe[nginx::openssl_source]
